### ISSUE TITLE
Request: AdaptaBreathNokto Colours

### ISSUE THREAD

**Issue by DakotaGunter** [RaitaroH/Userstyles-DeepDark#1]
Hello! I was hoping that you would add these colours to go along with the AdaptaBreathNokto theme on KDE and GTK. I already made the preset, so I believe adding this to the Style shouldn't be too difficult.

```css
/*AdaptaBreathNokto Colours*/               
                --main-color: #1abc9c;
		--main-background: #222d32;
		--second-background: #263238;
		--hover-background: #2a353b;
		--main-text: #ffffff;
		--dimmer-text: #9b9b9b;
		--shadow: 0 1px 0.5px rgba(0,0,0,0.13);

**Comment by RaitaroH** [comment]
Well, you can just select any color you want if you choose CUSTOM. So do `Main color: Custom` and then in the color selection right bellow you choose what you want. Is very simple. Is not just me adding those. I also need to go and add a var for each for stylus too. I will keep it in mind tho. I may just add it to my [swicher](https://gitlab.com/RaitaroH/Import-All-Deepdark/blob/master/switcher.user.css).

![screenshot_20180918_071108](https://user-images.githubusercontent.com/19552720/45663983-073c5500-bb12-11e8-80cd-38572c95eb63.png)

**Comment by RaitaroH** [comment]
@DakotaGunter 
[Here](https://gitlab.com/RaitaroH/Import-All-Deepdark/commit/79db875e82f9bd10964e3209f7042010b0d0776d) now you can select those easily.

P.S. Yes, I did move to gitlab, but I still check on here so don't worry. I was lazy to edit my readme files to point to gitlab :stuck_out_tongue_winking_eye:
