### ISSUE TITLE
List View still shows white

### ISSUE THREAD

**Issue by CodyMKW** [RaitaroH/Userstyles-DeepDark#2]
![chrome_2018-10-31_17-34-34](https://user-images.githubusercontent.com/8176523/47820248-5988ac80-dd33-11e8-947a-0b76f78535bf.png)

.us-stylecard--long 
Adding that where you have .us-stylecard--short should fix it

**Comment by RaitaroH** [comment]
Thanks. Fixed in https://github.com/RaitaroH/Userstyles-DeepDark/commit/52d54430cd42d1ccf9affb71de0c84dd95eb8003
